# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: task5
  pull_request:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build 
        run: cd task5 && mkdir 3rdparty && cd 3rdparty && git clone https://github.com/google/googletest.git && export GOOGLE_TEST_DIR="googletest" && cd .. && mkdir build && cd build && cmake .. && make && cd ..
          
      - {name: Test, uses: akhtyamovpavel/ActionGtestReport@v0.0.9, with: {exec-path: bin/CTestExe, report-path: report.xml, working-directory: task5/}}
        
      - name: UploadArtifacts
        uses: actions/upload-artifact@v2.2.3
        with: 
          name: Distributive    
          path: task5/bin/ && task5/lib/
